services:
  web:
    build: ./
    command: make run
    container_name: web
    volumes:
      - ./:/usr/src/app
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_NAME=postgres
      - DB_PORT=5432
      - DB_PASS=1234

  db:
    restart: always
    image: postgres:latest
    container_name: db
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
